[features]
seeds = false
[programs.localnet]
vote_program = "2emzK8JAJ2aUaW3NHjjcY1iyCWgDcSEWFepqhSqieYPA"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/chandan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
