[features]
seeds = false
[programs.localnet]
swap = "DxSNHynh4F2jzDwZWRGdaaMsv2JaQTCxG1jGmELbpkj7"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/chandan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
