[features]
seeds = false
[programs.localnet]
calculator = "Ca1cea21QUucyfugc8eY9kqVyofbm32Mz6zs1XdwmZYa"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/chandan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
